version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:   
      - apt-get update && apt-get install software-properties-common -y && add-apt-repository ppa:deadsnakes/ppa -y
      - apt-get update && apt-get install python3.9 -y
  build:
    commands:
      - echo "Scan is started ......"
  post_build:
    commands:
      - chmod +x ./scan.sh
      - ./scan.sh $sonar_url $sonar_user_name $sonar_password $github_token $github_repo_url $service_name $github_user_name $programming_language
  
